---
title: "4250 project table2"
author: "jy"
date: "April 3, 2016"
output: md_document
---

```{r,  message=FALSE, echo=FALSE}
library(MASS)
library(effects)
library(vcd)
library(car)
library(mlogit)
library(nnet)
library(ggplot2)
```

```{r,  message=FALSE, echo=FALSE}
Male <- read.csv("C:/Users/ASUS/Documents/MaleData.csv")

AGE1 <- cut(Male$Age, c(0.5, 1.5,2.5), labels = c("<=32",">32"))
OCCUPATION1 <- cut(Male$Occupation, c(0.5, 1.5,2.5,3.5,4.5,5.5, 6.5), labels = c("Manufacturing", "Construction", "Hospitality", "DomesticSservices", "SmallBusiness", "Recreation/Leisures"))
WORKPLACESCALE1 <- cut(Male$WorkplaceScale, c(0.5, 1.5,2.5,3.5), labels = c("Large","Moderate","Small"))
EDUCATIONATTAINMENT1 <- cut(Male$EducationalAttainment, c(0.5, 1.5,2.5,3.5,4.5), labels = c("Elementary/Lower","JuniorHigh","HighSchool","College"))
MARITALSTATUS1 <- cut(Male$MaritalStatus, c(0.5, 1.5,2.5,3.5,4.5), labels = c("Married", "Single","Cohabitating","Divorced/Widowed"))
ACCOMPANYCHILD1 <- cut(Male$AccompanyingChildren, c(0.5, 1.5,2.5,3.5), labels = c("NoChildren","Cohabitate","ResideElsewhere"))
SALARY1 <- cut(Male$Salary, c(0.5, 1.5,2.5,3.5,4.5), labels = c("<1500RMB","1500-2500RMB","2500-3500RMB",">=3500RMB"))
NUMBEROFCITIESRESIDEDIN1 <- cut(Male$NumberOfCitiesResidedIn, c(0.5, 1.5,2.5), labels = c("1-2", ">=3"))
DAILYWORKINGHOURS1 <- cut(Male$DailyWorkingHours, c(0.5, 1.5,2.5,3.5,4.5), labels = c("=8","<8","8-11",">=11"))
WEEKLYWORKINGDAYS1 <- cut(Male$WeeklyWorkingDaysX, c(0, 4.5,5.5,6.5,7.5), labels = c("<=4","5","6","7"))
RESIDENCE1 <- cut(Male$TypeOfResidence, c(0.5, 1.5,2.5,3.5,4.5,5.5), labels = c("CollectiveDormitory", "Rent(with others)", "Rent(family)", "Rent(alone)", "OwnLivingPlace"))
BMI1 <- cut(Male$BMI, c(-Inf, 18.49, 23.99, Inf), labels = c("Underweight", "NOrmalWeight", "Overweight"))
MENTALHEALTH1 <- cut(Male$MentalHealth, c(-Inf, 160.5, Inf), labels = c("Normal", "Abnormal"))

test1 <- glm(LifestyleScoreCategory~ AGE1 + OCCUPATION1 + WORKPLACESCALE1 + EDUCATIONATTAINMENT1 + MARITALSTATUS1  + ACCOMPANYCHILD1 + SALARY1 + NUMBEROFCITIESRESIDEDIN1 + DAILYWORKINGHOURS1 + WEEKLYWORKINGDAYS1 + RESIDENCE1 + BMI1 + MENTALHEALTH1, data = Male)
summary(test1)

ci1 <- confint(test1)

exp(cbind(COR = coef(test1), ci1))

plot(effect("OCCUPATION1", test1))
plot(effect("WORKPLACESCALE1", test1))
plot(effect("DAILYWORKINGHOURS1", test1))
plot(effect("MENTALHEALTH1", test1))

```

```{r,  message=FALSE, echo=FALSE}
Female <- read.csv("C:/Users/ASUS/Documents/FemaleData.csv")

AGE2 <- cut(Female$Age, c(0.5, 1.5,2.5), labels = c("<=32",">32"))
OCCUPATION2 <- cut(Female$Occupation, c(0.5, 1.5,2.5,3.5,4.5,5.5, 6.5), labels = c("Manufacturing", "Construction", "Hospitality", "DomesticSservices", "SmallBusiness", "Recreation/Leisures"))
WORKPLACESCALE2 <- cut(Female$WorkplaceScale, c(0.5, 1.5,2.5,3.5), labels = c("Large","Moderate","Small"))
EDUCATIONATTAINMENT2 <- cut(Female$EducationalAttainment, c(0.5, 1.5,2.5,3.5,4.5), labels = c("Elementary/Lower","JuniorHigh","HighSchool","College"))
MARITALSTATUS2 <- cut(Female$MaritalStatus, c(0.5, 1.5,2.5,3.5,4.5), labels = c("Married", "Single","Cohabitating","Divorced/Widowed"))
ACCOMPANYCHILD2 <- cut(Female$AccompanyingChildren, c(0.5, 1.5,2.5,3.5), labels = c("NoChildren","Cohabitate","ResideElsewhere"))
SALARY2 <- cut(Female$Salary, c(0.5, 1.5,2.5,3.5,4.5), labels = c("<1500RMB","1500-2500RMB","2500-3500RMB",">=3500RMB"))
NUMBEROFCITIESRESIDEDIN2 <- cut(Female$NumberOfCitiesResidedIn, c(0.5, 1.5,2.5), labels = c("1-2", ">=3"))
DAILYWORKINGHOURS2 <- cut(Female$DailyWorkingHours, c(0.5, 1.5,2.5,3.5,4.5), labels = c("=8","<8","8-11",">=11"))
WEEKLYWORKINGDAYS2 <- cut(Female$WeeklyWorkingDaysX, c(0, 4.5,5.5,6.5,7.5), labels = c("<=4","5","6","7"))
RESIDENCE2 <- cut(Female$TypeOfResidence, c(0.5, 1.5,2.5,3.5,4.5,5.5), labels = c("CollectiveDormitory", "Rent(with others)", "Rent(family)", "Rent(alone)", "OwnLivingPlace"))
BMI2 <- cut(Female$BMI, c(-Inf, 18.49, 23.99, Inf), labels = c("Underweight", "NOrmalWeight", "Overweight"))
MENTALHEALTH2 <- cut(Female$MentalHealth, c(-Inf, 160.5, Inf), labels = c("Normal", "Abnormal"))

test2 <- glm(LifestyleScoreCategory~ AGE2 + OCCUPATION2 + WORKPLACESCALE2 + EDUCATIONATTAINMENT2 + MARITALSTATUS2  + ACCOMPANYCHILD2 + SALARY2 + NUMBEROFCITIESRESIDEDIN2 + DAILYWORKINGHOURS2 + WEEKLYWORKINGDAYS2 + RESIDENCE2 + BMI2 + MENTALHEALTH2, data = Female)
summary(test2)

ci2 <- confint(test2)

exp(cbind(COR = coef(test2), ci2))

plot(effect("OCCUPATION2", test2))
plot(effect("MARITALSTATUS2", test2))
plot(effect("SALARY2", test2))
plot(effect("NUMBEROFCITIESRESIDEDIN2", test2))
plot(effect("DAILYWORKINGHOURS2", test2))
plot(effect("MENTALHEALTH2", test2))
```

