---
title: "4250 project table1"
author: "jy"
date: "March 30, 2016"
output: md_document
---
```{r,  message=FALSE, echo=FALSE}
library(MASS)
library(effects)
library(vcd)
library(car)
library(mlogit)
library(nnet)
```

```{r,  message=FALSE, echo=FALSE}
health <- read.csv("C:/Users/ASUS/Documents/Health-related lifestyle behaviors among male and female rural-to-urban migrant workers in Shanghai, China.csv")
Age <- table(health$Age, health$Gender)
dimnames(Age) <- list(Age = c("<=32",">32"), Gender = c("Male","Female"))

Age

chisq.test(Age,correct=F)

plot(effect("Age:Gender", health), style = 'stacked')

```

```{r,  message=FALSE, echo=FALSE}
Occupation <- table(health$Occupation, health$Gender)
dimnames(Occupation) <- list(Occupation = c("Manufacturing","Construction","Hospitality","Domestic service", "Small business","Recreation/leisure"), Gender = c("Male","Female"))

Occupation

chisq.test(Occupation,correct=F)

```

```{r,  message=FALSE, echo=FALSE}
WorkplaceScale <- table(health$WorkplaceScale, health$Gender)
dimnames(WorkplaceScale) <- list(WorkplaceScale = c("Large","Moderate","Small"), Gender = c("Male","Female"))

WorkplaceScale

chisq.test(WorkplaceScale,correct=F)

```

```{r,  message=FALSE, echo=FALSE}
EducationalAttainment <- table(health$EducationalAttainment, health$Gender)
dimnames(EducationalAttainment) <- list(EducationalAttainment = c("Elementary or lower","Junior high school","High school","College"), Gender = c("Male","Female"))

EducationalAttainment

chisq.test(EducationalAttainment,correct=F)

```

```{r,  message=FALSE, echo=FALSE}
MaritalStatus <- table(health$MaritalStatus, health$Gender)
dimnames(MaritalStatus) <- list(MaritalStatus = c("Married","Single","Cohabitating","Divorced or widowed"), Gender = c("Male","Female"))

MaritalStatus

chisq.test(MaritalStatus,correct=F)

```

```{r,  message=FALSE, echo=FALSE}
AccompanyingChildren <- table(health$AccompanyingChildren, health$Gender)
dimnames(AccompanyingChildren) <- list(AccompanyingChildren = c("No children","Cohabitating children","Children residing elsewhere"), Gender = c("Male","Female"))

AccompanyingChildren

chisq.test(AccompanyingChildren,correct=F)

```
```{r,  message=FALSE, echo=FALSE}
Salary <- table(health$Salary, health$Gender)
dimnames(Salary) <- list(Salary = c("<1500RMB","1500-2500RMB","2500-3500RMB",">=3500RMB"), Gender = c("Male","Female"))

Salary

chisq.test(Salary,correct=F)

```
```{r,  message=FALSE, echo=FALSE}
NumberOfCitiesResidedIn <- table(health$NumberOfCitiesResidedIn, health$Gender)
dimnames(NumberOfCitiesResidedIn) <- list(NumberOfCitiesResidedIn = c("1-2", ">=3"), Gender = c("Male","Female"))

NumberOfCitiesResidedIn

chisq.test(NumberOfCitiesResidedIn,correct=F)

```
```{r,  message=FALSE, echo=FALSE}
DailyWorkingHours <- table(health$DailyWorkingHours, health$Gender)
dimnames(DailyWorkingHours) <- list(DailyWorkingHours = c("<8","8","8-11",">=11"), Gender = c("Male","Female"))

DailyWorkingHours

chisq.test(DailyWorkingHours,correct=F)

```
```{r,  message=FALSE, echo=FALSE}
WeeklyWorkingDays <- table(health$WeeklyWorkingDays, health$Gender)
dimnames(WeeklyWorkingDays) <- list(WeeklyWorkingDays = c("<=4","5","6","7"), Gender = c("Male","Female"))

WeeklyWorkingDays

chisq.test(WeeklyWorkingDays,correct=F)

```
```{r,  message=FALSE, echo=FALSE}
TypeOfResidence <- table(health$TypeOfResidence, health$Gender)
dimnames(TypeOfResidence) <- list(TypeOfResidence = c("Collective dormitory", "Renting with others", "Renting as a family", "Renting alone", "Owning a living place"), Gender = c("Male","Female"))

TypeOfResidence

chisq.test(TypeOfResidence,correct=F)

```

